# Generated by Django 5.2 on 2025-04-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('consumer', 'Consumer Loan'), ('mortgage', 'Mortgage'), ('car', 'Car Loan'), ('business', 'Business Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term_months', models.IntegerField()),
                ('total_repayment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.TextField(blank=True, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('special_offers', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank')),
            ],
        ),
    ]
